### ISSUE TITLE
Router does not work in SAM local

### ISSUE THREAD

**Issue by napicella** [spring-media/aws-lambda-router#22]
The url normalization breaks the url when running the lambda in SAM local.
This happens because when using sam local the host is set to localhost.

I ve sent a pull request to address the issue.
More details in the pr https://github.com/spring-media/aws-lambda-router/pull/20

Thanks,
Nicola

**Comment by chgohlke** [comment]
Hi Nicola, i merged the PR #20 and released a new version 0.6.1. Thanks for your contribution.

**Comment by napicella** [comment]
Thank you!
