### ISSUE TITLE
error mapping is not working 

### ISSUE THREAD

**Issue by mohitp-cci** [spring-media/aws-lambda-router#24]
I have added the below code
    debug: true,
    errorMapping: {
      'NotFound': 404,
      'ServerError': 500,
    },

but it fails to map the error.

**Comment by chgohlke** [comment]
Hi @mohitp-cci 

here is an example of how we use errormapping (hint: this is not a working example):

```
exports.handler = router.handler({
    proxyIntegration: {
        routes: [
            {
                path: '/:id',
                method: 'GET',
                action: request => {
                    return getArticle(request.paths.id.toString());
                }
            }
        ],
        errorMapping: {
            'NotFound': 404,
            'RequestError': 400,
            'ServerError': 500
        }
    }
});

function getArticle(id) {
    throw { reason: 'ServerError', message: `Failed to get article ${id.toString()}` }
}
```

The **key** in the errormapping map must be the same as in the **reason key** of error message.

How did you do that in your code?

**Comment by mohitp-cci** [comment]
@chgohlke i had not added  throw { reason: 'ServerError', message: `Failed to get article ${id.toString()}` } 
adding this line fixed the issue. Thanks for the Help.

**Comment by chgohlke** [comment]
Ah, ok. I will improve the documentation at this point.
