### ISSUE TITLE
Question: When will a 6.3 release be pushed to NPM?

### ISSUE THREAD

**Issue by brianhyder** [spring-media/aws-lambda-router#28]
Hey all,

  I'm really liking the simplicity of this package.  I ran into a snag the other night because the latest published version of the package on NPM (0.6.2) didn't contain a change that is currently in the master branch.  Specifically, the change to the proxy integrations's `isLocalExecution` implementation.
https://github.com/spring-media/aws-lambda-router/blame/master/lib/proxyIntegration.js#L203

I would like to avoid adding a specific commit to our `package.json` or forking the repo.  

Thanks for the consideration!

**Comment by chgohlke** [comment]
Hey @brianhyder 

thanks for your interest in the lambda router. We are currently working on a Typescript migration and will release the new version in a week or two or so. 

In the meantime I can put a small minor release in between if you need it.

**Comment by brianhyder** [comment]
That's awesome to hear. If the runway is a week or two it shouldn't be an issue.  I appreciate the quick response and look forward to the next release.

**Comment by chgohlke** [comment]
All right. If we need longer for the release train, I will create a minor release.

**Comment by chgohlke** [comment]
Hi @brianhyder, I just deployed a new version (0.7.0). Have fun trying it out. If there are any bugs or suggestions, feel free to contact me or open an issue.

**Comment by chgohlke** [comment]
Take a look at version 0.8.1. This is the newest version with some improvements. I will now close this issue.
