### ISSUE TITLE
ProxyIntegrationRoute.action() has incorrect type signature

### ISSUE THREAD

**Issue by aparker-csaa** [spring-media/aws-lambda-router#35]
Hi, `request.body` is typed as `string | null`. This is incorrect as `request.body` is being JSON-decoded.

The workaround:

```
const body =
  req.body === null
    ? undefined
    : ((req.body as unknown) as CreateUserRequest);
```

Is undesirable. Perhaps updating the typing for `ProxyIntegrationParams` is necessary, adding `body: object`?

**Comment by chgohlke** [comment]
Hi @aparker-csaa, you're right. We're working on a new version, fixing this issue, among other things. Stay tuned. We'll be releasing soon.

**Comment by tdt17** [comment]
Hi @aparker-csaa, take a look at 0.8.1. We improved the type of the body and added 2 examples in our readme. It's now possible to set a custom type for the body:
```
action: (request: ProxyIntegrationEvent<{ text: string }>, context) => {
   return `You called me with: ${request.body.text}`
}
```
