### ISSUE TITLE
add sqs message attributes

### ISSUE THREAD

**Issue by gloced** [spring-media/aws-lambda-router#38]
would be great to also pass sqs message attributes to the action, not just the body

**Comment by chgohlke** [comment]
Hi @gloced 

that's an great idea. Here is an example of an SNS event with message attributes:

```{
  'Records': [
    {
      'EventSource': 'aws:sns',
      'EventVersion': '1.0',
      'EventSubscriptionArn': 'arn:aws:sns:eu-central-1:acountId:name:447fc2be2',
      'Sns': {
        'Type': 'Notification',
        'MessageId': 'f654de89-6d8d-53a3-bbe4-8bf433c4e3ae',
        'TopicArn': 'arn:aws:sns:eu-central-1:acountId:name',
        'Subject': 'Change Event',
        'Message': '{"requestId":"a936b78f4","payload":[{"eventStatus":"MODIFIED"}]}',
        'Timestamp': '2019-06-14T08:34:17.065Z',
        'SignatureVersion': '1',
        'Signature': 'AfIFalzyDh2+JRM9NFVlUXKCcrZaDLWI6TvuV3WCg==',
        'SigningCertUrl': 'https://sns.eu-central-1.amazonaws.com/SimpleNotificationService-6aad65.pem',
        'UnsubscribeUrl': 'https://sns.eu-central-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=short-arn',
        'MessageAttributes': '{
                    "stringAttribute": {
                        "Type": "String",
                        "Value": "stringvalue"
                    },
                    "binaryAttribute": {
                        "Type": "Binary",
                        "Value": "Ym9udmFsdWU="
                    },
                    "arrayAttribute": {
                        "Type": "String",
                        "Value": "[\"value1\", \"value2\"]"
                    }
                }'
      }
    }
  ]
}
```



In this example the item `MessageAttribute` contains SNS Message Attributes as desribed in the documentation here:

https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html

In the first approach I would forward the message attributes directly without parsing them. Do you have another idea? Maybe check certain rules (that you could configure) on the attributes or something?

**Comment by gloced** [comment]
Hi @chgohlke 

I had a look at lib/sqs.js. The following line reduces the whole message object to just the body.

> const result = routeConfig.action(records.map(record => record.body) , context);

Adding the whole, unparsed Message to the configured action would be a breaking change. To maybe avoid a breaking change would be to add a config variable "passWholeSQSMessage" which defaults to false. In this case one could choose to process the whole message or just the body.

**Comment by chgohlke** [comment]
Hi @gloced, here is an PR #43 to address this issue. To avoid breaking changes, we add the records array as 3rd parameter to the action method. What do you think?
