### ISSUE TITLE
No Custom Uncaught Error Handling

### ISSUE THREAD

**Issue by nicovigil1** [spring-media/aws-lambda-router#41]
In trying to implement aws-lambda-router alongside honeybadger, I realized that there's no real way to catch uncaught errors as everything is caught. It would be nice to have an option to allow for uncaught errors, so that things like Honeybadger can report on unexpected behavior. 

An additional solution may include allowing users to define their own function that get run in a `catch`.

**Comment by rafaelmotaalves** [comment]
I would like to implement this feature, how would this function work? would it be executed when there is no error defined like it on the error mapping or would it be an alternative to the errorMapping option?

I think the better option would be the first because if the user doesn`t define an errorMapping objects all errors would be redirected to this catch function.

**Comment by nicovigil1** [comment]
I agree, that way you have the option for both in case you don't care about uncaught errors. Looking forward to see how this turns out!

**Comment by chgohlke** [comment]
Hi @rafaelmotaalves! Fell free to implement (pls with tests). I think it would be really good if you could take care of it. Unfortunately i don't have that much time for it.

**Comment by BabyDino** [comment]
I use this with middy. I was using the [http-error-handler](https://github.com/middyjs/middy/tree/master/packages/http-error-handler) together with [http-errors](https://github.com/jshttp/http-errors). Unfortunately it doesn't work well with `aws-lambda-router`. Switching off the error handler would be helpful. I am currently switching to the built-in error handler of `aws-lambda-router` but more options would be appreciated. Maybe add `http-errors` support so we don't have to define the errorMapping?

**Comment by swaner** [comment]
PR regarding this:
#60
