### ISSUE TITLE
Custom CORS Headers

### ISSUE THREAD

**Issue by brianhyder** [spring-media/aws-lambda-router#51]
We have a need to be able to modify the default CORS headers to support specific domains for the allowed origin.  We'd prefer to avoid having to add these headers in each handler or as middleware, if possible.  

A possible solution:
Allow for a handler (anonymous function or arrow function) to be assigned to the `cors` variable or another variable in the proxy configuration.  That handler would be responsible for setting the header values as shown [here](https://github.com/spring-media/aws-lambda-router/blob/master/lib/proxyIntegration.ts#L52) or return an object with the key values that could be merged with the other headers.  

This would allow for the handy option, to handle all OPTIONS requests, to stay in place but provide a greater level of customization for each use-case.  The default behavior could be to use the existing function that sets the headers if no implementation is provided.

**Comment by chgohlke** [comment]
Hi @brianhyder great idea! I also think that the router is not yet well configurable (see also Issue #41). So the router has to be improved here in the future.

Can you create a PR for it, how you could imagine that?

**Comment by brianhyder** [comment]
Hey, I think a PR would be doable.  I'm working with my team to see if we can get it into an upcoming sprint.
