### ISSUE TITLE
Release 0.9.1?

### ISSUE THREAD

**Issue by TerryMooreII** [spring-media/aws-lambda-router#54]
Any change you can release the latest code merges with a new npm version? #53

**Comment by chgohlke** [comment]
Hi @TerryMooreII, I can create a new release. Are there any changes on your part to wait for a release? If not, I would create a release.

**Comment by TerryMooreII** [comment]
We dont have any more changes at this time.  Thanks for all you hard work on this project, we appreciate it!

**Comment by chgohlke** [comment]
This issue can be closed now. I released version 0.9.1
