### ISSUE TITLE
Log Event Data an Response for Every Request

### ISSUE THREAD

**Issue by DorZuberi** [spring-media/aws-lambda-router#80]
Hello,
Is there a way to log the event data and the response of the route on every API call?

**Comment by xianqugithub** [comment]
I don't think this library has it. You might consider using other tools such as 
https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/

**Comment by DorZuberi** [comment]
Hi @xianqugithub 
Thanks for the reply, but i ended up wrapping AWS Lambda Router with my own backend library.
